---
- name: install dependencies | Debian
  package:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - openssl
  when: ansible_os_family == "Debian"

- name: install dependencies | RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openssl
  when: ansible_os_family == "RedHat"

