---
- name: Install dependencies | Debian
  package:
    pkg: "{{ item }}"
    update_cache: true
    cache_valid_time: 86400
    state: present
  with_items:
    - openssl
    - libpcap-dev
    - libpq-dev
  when: ansible_os_family == "Debian"

- name: Install dependencies | RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openssl
    - libpcap
    - postgresql-libs
  when: ansible_os_family == "RedHat"
