---
- name: "Gather os specific variables {{ ansible_distribution }} - {{ ansible_distribution_major_version }}"
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"

# ---------------------------------------------
# Install dependencies
# ---------------------------------------------
- name: Install dependencies
  import_tasks: dependencies.yml
  become: true

# --------------------------------------------------
# Create user/group
# --------------------------------------------------
- name: "Add miarec group '{{ miarec_screen_bin_group }}'"
  group:
    name: "{{ miarec_screen_bin_group }}"
    state: present
  when: miarec_screen_bin_group != 'root'

- name: "Add miarec user '{{ miarec_screen_bin_user }}'"
  user:
    name: "{{ miarec_screen_bin_user }}"
    group: "{{ miarec_screen_bin_group }}"
    comment: "MiaRec"
    shell: /bin/false
    system: true
  when: miarec_screen_bin_user != 'root'

# --------------------------------------------------
# Initialize the installation/upgrade process
# --------------------------------------------------
- name: Initialize the deploy root and gather facts
  deploy_helper:
    path: "{{ miarec_screen_install_dir }}"
    release: "{{ miarec_screen_version }}"
    mode: u=rwX,g=rX,o=rX
  become: true

# --------------------------------------------------
# Install/upgrade 'miarec' app files
# --------------------------------------------------
- name: Install miarec_screen
  import_tasks: install.yml
  become: true

# --------------------------------------------------
# Cleanup old and unfinished releases
# --------------------------------------------------
- name: Cleanup old releases
  deploy_helper:
    path: "{{ miarec_screen_install_dir }}"
    release: '{{ deploy_helper.new_release }}'
    state: finalize
    keep_releases: 10
  notify:
    - Restart miarec_screen
  become: true
