---
- name: "Gather os specific variables ({{ ansible_distribution }} - {{ ansible_distribution_major_version }})"
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"

# ---------------------------------------------
# Install dependencies
# ---------------------------------------------
- include: dependencies.yml

# --------------------------------------------------
# Initialize the installation/upgrade process
# --------------------------------------------------
- name: Initialize the deploy root and gather facts
  deploy_helper:
    path: "{{ miarec_screen_install_dir }}"
    release: "{{ miarec_screen_version }}"

# --------------------------------------------------
# Install/upgrade 'miarec' app files
# --------------------------------------------------
- include: install.yml

# --------------------------------------------------
# Cleanup old and unfinished releases
# --------------------------------------------------
- name: Cleanup old releases
  deploy_helper:
    path: "{{ miarec_screen_install_dir }}"
    release: '{{ deploy_helper.new_release }}'
    state: finalize
    keep_releases: 10
  notify: 
    - restart miarec_screen


