---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: miarecdevops/docker-${MOLECULE_DISTRO:-ubuntu2204}-init:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
    MIAREC_SCREEN_VERSION: ${MOLECULE_MIAREC_SCREEN_VERSION:-"1.1.0.46"}

# verifier:
#   name: testinfra
#   options:
#     s: true
#     verbose: true